package com.webtestautomationframework.utils;

public enum ToolConfigProperties {
    PROJECT_URL,
    IS_REMOTE_SERVER_URL_DEFINED,
    HUB_URL,
    BROWSER_TYPE,
    BROWSER_DOWNLOAD_PATH,
    CHROME_BROWSER_FLAGS,
    PATH_CHROME_DRIVER_SERVER_EXE,
    PATH_CHROME_DRIVER_SERVER,
    PATH_EDGE_DRIVER_SERVER_EXE,
    PATH_GECKO_DRIVER_EXE,
    PATH_GECKO_DRIVER,
    GIF_FILE_PATH,
    GIFFER
}
